
> gp2040-configurator@0.1.0 dev
> concurrently --kill-others "npm run dev-server" "npm start"

[0]
[0] > gp2040-configurator@0.1.0 dev-server
[0] > nodemon -r dotenv/config ./server/app.js
[0]
[1]
[1] > gp2040-configurator@0.1.0 start
[1] > npm run build-proto && vite
[1]
[0] [33m[nodemon] 2.0.22[39m
[0] [33m[nodemon] to restart at any time, enter `rs`[39m
[0] [33m[nodemon] watching path(s): *.*[39m
[0] [33m[nodemon] watching extensions: js,mjs,json[39m
[0] [32m[nodemon] starting `node -r dotenv/config ./server/app.js`[39m
[1]
[1] > gp2040-configurator@0.1.0 build-proto
[1] > npm run build-proto:enums && npm run build-proto:config
[1]
[0] node:events:496
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
[0]     at Server.setupListenHandle [as _listen2] (node:net:1940:16)
[0]     at listenInCluster (node:net:1997:12)
[0]     at Server.listen (node:net:2102:7)
[0]     at Function.listen (/app/www/node_modules/express/lib/application.js:635:24)
[0]     at file:///app/www/server/app.js:828:5
[0]     at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
[0]     at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
[0]     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1976:8)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '0.0.0.0',
[0]   port: 8080
[0] }
[0]
[0] Node.js v22.17.1
[0] [31m[nodemon] app crashed - waiting for file changes before starting...[39m
[1]
[1] > gp2040-configurator@0.1.0 build-proto:enums
[1] > npx pbjs --no-create --no-encode --no-decode --no-convert --no-verify --no-delimited --sparse -t static-module -w commonjs --path ../lib/nanopb/generator/proto/ ../proto/enums.proto | npx pbts --no-comments -m -o ./src_gen/enums.ts -
[1]
[1]
[1] > gp2040-configurator@0.1.0 build-proto:config
[1] > npx pbjs --no-create --no-encode --no-decode --no-convert --no-verify --no-delimited --sparse -t static-module -w commonjs --path ../lib/nanopb/generator/proto/ ../proto/config.proto | npx pbts --no-comments -m -o ./src_gen/config.ts -
[1]
[0] [32m[nodemon] restarting due to changes...[39m
[0] [32m[nodemon] starting `node -r dotenv/config ./server/app.js`[39m
[0] node:events:496
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
[0]     at Server.setupListenHandle [as _listen2] (node:net:1940:16)
[0]     at listenInCluster (node:net:1997:12)
[0]     at Server.listen (node:net:2102:7)
[0]     at Function.listen (/app/www/node_modules/express/lib/application.js:635:24)
[0]     at file:///app/www/server/app.js:828:5
[0]     at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
[0]     at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
[0]     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1976:8)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -98,
[0]   syscall: 'listen',
[0]   address: '0.0.0.0',
[0]   port: 8080
[0] }
[0]
[0] Node.js v22.17.1
[0] [31m[nodemon] app crashed - waiting for file changes before starting...[39m
[1]
[1]   VITE v4.3.9  ready in 513 ms
[1]
[1]   âžœ  Local:   http://localhost:3000/
